Upgrade to core-js@^3.3.0 to fix Android 4.4 compatibility (#723) https://github.com/uber/fusionjs/pull/723
We're seeing 4521 occurrences in the past month:

```
Error: at emitOne (events.js:121:20): Cannot redefine property: then

stack
at defineProperty (native)
    nativeDefineProperty at /home/udocker/web-payments-experience/node_modules/fusion-cli/node_modules/core-js/modules/es.symbol.js:104:11
    f at /home/udocker/web-payments-experience/node_modules/fusion-cli/node_modules/core-js/internals/hide.js:6:30
    hide at /home/udocker/web-payments-experience/node_modules/fusion-cli/node_modules/core-js/internals/redefine.js:35:7
    redefine at /home/udocker/web-payments-experience/node_modules/fusion-cli/node_modules/core-js/modules/es.promise.js:281:4
    call at /home/udocker/web-payments-experience/webpack/bootstrap:84:21
    Object.push.jWX+ at https://d3i4yxtzktqr9n.cloudfront.net/web-payments-experience/client-legacy-vendor-6fa8dbaec985031d91bc.js:81:61695
    call at /home/udocker/web-payments-experience/webpack/bootstrap:84:21
    Object.push at https://d3i4yxtzktqr9n.cloudfront.net/web-payments-experience/client-legacy-main-5702507d1dcffd2fe721.js:1:1206
    call at /home/udocker/web-payments-experience/webpack/bootstrap:84:21
```

Seems to be caused by https://github.com/zloirock/core-js/issues/640, which affects Android 4.4 devices, which is the minimum support version at Uber.

Upgraded by running the following commands:
```
cd public/fusion-cli/
jazelle upgrade core-js@^3.3.0
```

Co-authored-by: Ryan Tsao <rtsao@uber.com>