Resolve 'graphql' to a single version (v14.5.4) (#577) https://github.com/uber/fusionjs/pull/577
Ensures `graphql` dependency is resolved to a single version.  Prior to this, `yarn list` yielded:

```sh
$ yarn list graphql
yarn list v1.13.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @types/graphql-upload@8.0.3
│  └─ graphql@14.5.4
├─ @uber/typed-rpc-cli@2.3.0
│  └─ graphql@14.5.4
├─ apollo-language-server@1.15.3
│  └─ graphql@14.5.4
├─ apollo@2.18.3
│  └─ graphql@14.5.4
└─ graphql@14.5.7
✨  Done in 0.87s.
```

Which triggered the following warning and error:

(Warning)
```sh
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

(Error)
```sh
TypeError: _schema.then is not a function
    at new ApolloServerBase (/Users/amsmith/Code/Misc/test-proj/node_modules/apollo-server-koa/node_modules/apollo-server-core/src/ApolloServer.ts:365:40)
    at new ApolloServer (/Users/amsmith/Code/Misc/test-proj/node_modules/apollo-server-koa/src/ApolloServer.ts:71:1)
    at Object.middleware (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-plugin-apollo/dist/index.js:142:22)
    at resolvePlugin (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:567:39)
    at enhancers.forEach.e (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:600:28)
    at Array.forEach (<anonymous>)
    at resolveToken (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:588:19)
    at resolvePlugin (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:560:31)
    at resolveToken (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:576:20)
    at App.resolve (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:613:7)
    at App.resolve (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:932:20)
    at App.callback (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-core/dist/index.js:936:12)
    at reload (/Users/amsmith/Code/Misc/test-proj/node_modules/fusion-cli/entries/server-entry.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at evalScript (internal/bootstrap/node.js:592:13)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```