Handle legacy query params in translations requests (#508) https://github.com/uber/fusionjs/pull/508
Requests with the legacy query params will cause an uncaught exception:

`TypeError: keys.reduce is not a function at /home/udocker/web-eats-v2/node_modules/fusion-plugin-i18n/dist/index.js:216:35 at process._tickCallback (internal/process/next_tick.js:68:7)`

In order for gradual rollouts we need to still handle the legacy requests from clients that are older than the server.

Duplicate PR since last branch had a `/` in it.

Co-authored-by: Brendan Dean <bdean@uber.com>
Co-authored-by: Derek Ju <derek.ju@gmail.com>
Co-authored-by: UberOpenSourceBot <UberOpenSourceBot@users.noreply.github.com>